//! Synthetic seed library for the LAB stack (SKADI-T-0392 / SKADI-T-0393).
//!
//! Generates `count` multi-file torrents of random data under the lab storage
//! dir, laid out exactly the way the worker leaves a finished download
//! (`downloads/incomplete/<name>/…` hardlinked into `downloads/complete/<name>/…`),
//! writes each `.torrent` next to them and emits one SQL file that inserts a
//! `completed` `downloads` row per torrent — so on its next start the lab worker
//! re-attaches every one of them as a seed (re-add from the local `.torrent`,
//! full hash-check, then live) with no internet and no peers. That reproduces
//! the load shape behind the ~9 GB prod worker (hundreds of torrents, thousands
//! of open files, hash-checks) on local disk in minutes.
//!
//! Run from the repo root (the worker crate is outside the workspace):
//!
//! ```text
//! cargo run --release --manifest-path crates/skadi-downloader-worker/Cargo.toml \
//!     --example synth_library -- --count 300 --files 24 --file-mib 1 --piece-kib 512
//! docker compose -p skadi-lab exec -T postgres psql -U skadi -d skadi \
//!     < deploy/.lab/storage/skadi/lab-torrents/seed-rows.sql
//! docker compose -p skadi-lab restart skadi-downloader-worker
//! ```
//!
//! Options (all optional): `--root <dir>` (default `deploy/.lab/storage`),
//! `--count N`, `--files F` per torrent, `--file-mib M` per file, `--piece-kib P`,
//! `--worker-id <id>` (default `skadi-lab-worker-1`, must match `.env.lab`).
//! Re-running is idempotent per name: existing torrents are skipped.

use std::fmt::Write as _;
use std::fs;
use std::io::Write as _;
use std::path::PathBuf;

use librqbit::{CreateTorrentOptions, create_torrent};

/// Container-side mount of `--root` (see deploy/docker-compose.lab.yml).
const CONTAINER_ROOT: &str = "/mnt/storage";

struct Opts {
    root: PathBuf,
    count: usize,
    files: usize,
    file_mib: usize,
    piece_kib: u32,
    worker_id: String,
}

fn parse_opts() -> Opts {
    let mut o = Opts {
        root: PathBuf::from("deploy/.lab/storage"),
        count: 300,
        files: 24,
        file_mib: 1,
        piece_kib: 512,
        worker_id: "skadi-lab-worker-1".into(),
    };
    let mut args = std::env::args().skip(1);
    while let Some(flag) = args.next() {
        let val = args
            .next()
            .unwrap_or_else(|| panic!("{flag} needs a value"));
        match flag.as_str() {
            "--root" => o.root = PathBuf::from(val),
            "--count" => o.count = val.parse().expect("--count"),
            "--files" => o.files = val.parse().expect("--files"),
            "--file-mib" => o.file_mib = val.parse().expect("--file-mib"),
            "--piece-kib" => o.piece_kib = val.parse().expect("--piece-kib"),
            "--worker-id" => o.worker_id = val,
            other => panic!("unknown flag {other}"),
        }
    }
    o
}

/// xorshift64* — fast, dependency-free, and NOT compressible, which is all the
/// hash-checker cares about. Seeded per file so re-runs are reproducible.
fn fill_random(buf: &mut [u8], mut state: u64) {
    for chunk in buf.chunks_mut(8) {
        state ^= state >> 12;
        state ^= state << 25;
        state ^= state >> 27;
        let v = state.wrapping_mul(0x2545_F491_4F6C_DD1D).to_le_bytes();
        chunk.copy_from_slice(&v[..chunk.len()]);
    }
}

fn sql_str(s: &str) -> String {
    format!("'{}'", s.replace('\'', "''"))
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let o = parse_opts();
    let incomplete = o.root.join("skadi/downloads/incomplete");
    let complete = o.root.join("skadi/downloads/complete");
    let torrents = o.root.join("skadi/lab-torrents");
    fs::create_dir_all(&incomplete)?;
    fs::create_dir_all(&complete)?;
    fs::create_dir_all(&torrents)?;

    let mut sql = String::new();
    writeln!(
        sql,
        "-- generated by synth_library: {} torrents x {} files x {} MiB, {} KiB pieces\nbegin;",
        o.count, o.files, o.file_mib, o.piece_kib
    )?;

    let mut buf = vec![0u8; o.file_mib * 1024 * 1024];
    let mut made = 0usize;
    for i in 1..=o.count {
        let name = format!("lab-seed-{i:04}");
        let src_dir = incomplete.join(&name);
        let dst_dir = complete.join(&name);
        let torrent_path = torrents.join(format!("{name}.torrent"));
        if !torrent_path.exists() {
            fs::create_dir_all(&src_dir)?;
            fs::create_dir_all(&dst_dir)?;
            for f in 1..=o.files {
                let fname = format!("part-{f:02}.bin");
                let src = src_dir.join(&fname);
                fill_random(&mut buf, (i as u64) << 20 | f as u64);
                fs::File::create(&src)?.write_all(&buf)?;
                let dst = dst_dir.join(&fname);
                if !dst.exists() {
                    fs::hard_link(&src, &dst)?;
                }
            }
            let t = create_torrent(
                &src_dir,
                CreateTorrentOptions {
                    name: Some(&name),
                    piece_length: Some(o.piece_kib * 1024),
                },
            )
            .await?;
            fs::write(&torrent_path, t.as_bytes()?)?;
            made += 1;
        }
        let info_hash = {
            let bytes = fs::read(&torrent_path)?;
            let t: librqbit::TorrentMetaV1Borrowed<'_> = librqbit::torrent_from_bytes(&bytes)?;
            t.info_hash.as_string()
        };
        let total = (o.files * o.file_mib * 1024 * 1024) as u64;
        let files_json: Vec<String> = (1..=o.files)
            .map(|f| {
                format!("\"{CONTAINER_ROOT}/skadi/downloads/complete/{name}/part-{f:02}.bin\"")
            })
            .collect();
        writeln!(
            sql,
            "insert into downloads (id, acquirable_ref, source, category, status, info_hash, progress_bytes, total_bytes, files, worker_id, delete_data, incomplete_dir, complete_dir, created_at, updated_at, completed_at) \
             select gen_random_uuid(), {name_s}, {src_s}, '3030', 'completed', {hash_s}, {total}, {total}, '[{files}]'::jsonb, {worker_s}, false, '{root}/skadi/downloads/incomplete', '{root}/skadi/downloads/complete', now(), now(), now() \
             where not exists (select 1 from downloads where info_hash = {hash_s});",
            name_s = sql_str(&name),
            src_s = sql_str(&format!(
                "{CONTAINER_ROOT}/skadi/lab-torrents/{name}.torrent"
            )),
            hash_s = sql_str(&info_hash),
            files = files_json.join(","),
            worker_s = sql_str(&o.worker_id),
            root = CONTAINER_ROOT,
        )?;
        if i % 50 == 0 {
            eprintln!("{i}/{} torrents", o.count);
        }
    }
    writeln!(sql, "commit;")?;
    let sql_path = torrents.join("seed-rows.sql");
    fs::write(&sql_path, sql)?;
    eprintln!(
        "done: {made} new torrents ({} total), {} MiB each; rows in {}",
        o.count,
        o.files * o.file_mib,
        sql_path.display()
    );
    Ok(())
}
