//! Upload sessions end to end (SKADI-T-0628).
//!
//! The mechanics that matter are the ones a flaky connection exercises:
//! resuming from the server's high-water mark, re-sending a chunk that already
//! landed, and refusing a chunk that would leave a hole. Each is tested
//! against the real router rather than the helper functions, because the bugs
//! here live in the wiring — an offset misread from a query string is not
//! something a unit test of `safe_filename` would ever catch.

use std::sync::Arc;

use axum::body::Body;
use axum::http::{Request, StatusCode};
use http_body_util::BodyExt;
use skadi_store::ConfigRepo;
use skadi_store::ConfigSource;
use tower::ServiceExt;

use skadi_api::{AppState, Config};
use skadi_testsupport::TestDb;

fn config() -> Config {
    Config {
        database_url: "sqlite://:memory:".into(),
        bind_addr: "127.0.0.1:0".parse().unwrap(),
        bearer_token: Some("operator-token".into()),
    }
}

async fn call(
    state: &Arc<AppState>,
    method: &str,
    uri: &str,
    body: Option<serde_json::Value>,
) -> (StatusCode, serde_json::Value) {
    let req = Request::builder()
        .method(method)
        .uri(uri)
        .header("Authorization", "Bearer operator-token");
    let req = match body {
        Some(b) => req
            .header("content-type", "application/json")
            .body(Body::from(b.to_string()))
            .unwrap(),
        None => req.body(Body::empty()).unwrap(),
    };
    let res = skadi_api::router(state.clone()).oneshot(req).await.unwrap();
    let status = res.status();
    let bytes = res.into_body().collect().await.unwrap().to_bytes();
    (
        status,
        serde_json::from_slice(&bytes).unwrap_or(serde_json::Value::Null),
    )
}

/// Send raw bytes at an offset, the way the browser will.
async fn put_chunk(
    state: &Arc<AppState>,
    id: &str,
    offset: u64,
    bytes: &[u8],
) -> (StatusCode, serde_json::Value) {
    let req = Request::builder()
        .method("PUT")
        .uri(format!("/api/v1/uploads/{id}/chunk?offset={offset}"))
        .header("Authorization", "Bearer operator-token")
        .header("content-type", "application/octet-stream")
        .body(Body::from(bytes.to_vec()))
        .unwrap();
    let res = skadi_api::router(state.clone()).oneshot(req).await.unwrap();
    let status = res.status();
    let body = res.into_body().collect().await.unwrap().to_bytes();
    (
        status,
        serde_json::from_slice(&body).unwrap_or(serde_json::Value::Null),
    )
}

/// A state whose `library.root` is a real directory, since that is where
/// uploads must land — see SKADI-I-0062 on why staging cannot be elsewhere.
async fn state_with_root() -> (Arc<AppState>, TestDb, tempfile::TempDir) {
    let db = TestDb::new_store_only().await;
    let dir = tempfile::tempdir().unwrap();
    db.store
        .set_config(
            "library.root",
            &dir.path().display().to_string(),
            ConfigSource::Runtime,
        )
        .await
        .unwrap();
    let state = AppState::new_full(config(), Some(db.store.clone()), vec![], vec![]);
    state.refresh_members().await;
    (state, db, dir)
}

/// A real WAV, generated by a canonical writer rather than hand-assembled.
///
/// The tests that run all the way to completion need bytes the probe can
/// actually read, because an upload now has to prove it is media before it can
/// be adopted (SKADI-T-0629). My first attempt at synthesising a WAV header
/// inline produced a file `lofty` refused — which is the check doing its job,
/// and a good reminder that "looks like a valid header" is not the same as
/// "a decoder accepts it". The fixture removes that guesswork from the test.
fn tiny_wav() -> Vec<u8> {
    include_bytes!("fixtures/tone.wav").to_vec()
}

fn sha256_hex(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let mut h = Sha256::new();
    h.update(bytes);
    h.finalize().iter().map(|b| format!("{b:02x}")).collect()
}

/// Open a session for a real audiobook file.
async fn open_audio(state: &Arc<AppState>, name: &str, size: usize) -> serde_json::Value {
    let (st, v) = call(
        state,
        "POST",
        "/api/v1/uploads",
        Some(serde_json::json!({
            "filename": name, "size_bytes": size, "kind": "audiobook"
        })),
    )
    .await;
    assert_eq!(st, StatusCode::OK, "opening a session: {v}");
    v
}

async fn open(state: &Arc<AppState>, name: &str, size: usize) -> serde_json::Value {
    let (st, v) = call(
        state,
        "POST",
        "/api/v1/uploads",
        Some(serde_json::json!({
            "filename": name, "size_bytes": size, "kind": "movie"
        })),
    )
    .await;
    assert_eq!(st, StatusCode::OK, "opening a session: {v}");
    v
}

#[tokio::test]
async fn a_file_sent_in_chunks_arrives_whole() {
    let (state, _db, root) = state_with_root().await;
    let payload = tiny_wav();

    let s = open_audio(&state, "Some Book.wav", payload.len()).await;
    let id = s["id"].as_str().unwrap().to_string();
    assert_eq!(s["received_bytes"], 0);

    for part in payload.chunks(1000) {
        let have = call(&state, "GET", &format!("/api/v1/uploads/{id}"), None)
            .await
            .1["received_bytes"]
            .as_u64()
            .unwrap();
        let (st, v) = put_chunk(&state, &id, have, part).await;
        assert_eq!(st, StatusCode::OK, "{v}");
    }

    let (st, done) = call(
        &state,
        "POST",
        &format!("/api/v1/uploads/{id}/complete"),
        None,
    )
    .await;
    assert_eq!(st, StatusCode::OK, "{done}");

    // The bytes on disk are the bytes that were sent, in order.
    let path = done["path"].as_str().unwrap();
    assert!(
        path.starts_with(&root.path().display().to_string()),
        "staging must be under the library root, got {path}"
    );
    assert_eq!(std::fs::read(path).unwrap(), payload);
}

#[tokio::test]
async fn re_sending_a_chunk_that_already_landed_is_not_an_error() {
    // The case this exists for: the client sent a chunk, the server wrote it,
    // and the response was lost. The client must be able to re-send without
    // either failing or appending the same bytes twice.
    let (state, _db, _root) = state_with_root().await;
    let s = open(&state, "retry.mkv", 200).await;
    let id = s["id"].as_str().unwrap().to_string();

    let (st, _) = put_chunk(&state, &id, 0, &[7u8; 100]).await;
    assert_eq!(st, StatusCode::OK);
    let (st, v) = put_chunk(&state, &id, 0, &[7u8; 100]).await;
    assert_eq!(st, StatusCode::OK, "a retry must be accepted: {v}");
    assert_eq!(
        v["received_bytes"], 100,
        "the retry must not have been appended a second time"
    );
}

#[tokio::test]
async fn a_chunk_that_would_leave_a_hole_is_refused_and_says_where_to_resume() {
    let (state, _db, _root) = state_with_root().await;
    let s = open(&state, "hole.mkv", 500).await;
    let id = s["id"].as_str().unwrap().to_string();
    put_chunk(&state, &id, 0, &[1u8; 100]).await;

    // Skipping ahead would silently produce a file with 100 zero bytes in the
    // middle that still passed the size check at completion.
    let (st, v) = put_chunk(&state, &id, 200, &[1u8; 100]).await;
    assert_eq!(st, StatusCode::BAD_REQUEST, "{v}");
    assert!(
        v["message"].as_str().unwrap().contains("100"),
        "the error must name the resume point, got {v}"
    );
}

#[tokio::test]
async fn an_upload_resumes_from_what_the_server_actually_holds() {
    let (state, _db, _root) = state_with_root().await;
    let s = open(&state, "resume.mkv", 300).await;
    let id = s["id"].as_str().unwrap().to_string();
    put_chunk(&state, &id, 0, &[9u8; 120]).await;

    // Simulating the client coming back after a drop: ask, then continue.
    let (st, v) = call(&state, "GET", &format!("/api/v1/uploads/{id}"), None).await;
    assert_eq!(st, StatusCode::OK);
    assert_eq!(v["received_bytes"], 120);

    let (st, v) = put_chunk(&state, &id, 120, &[9u8; 180]).await;
    assert_eq!(st, StatusCode::OK, "{v}");
    assert_eq!(v["received_bytes"], 300);
}

#[tokio::test]
async fn completing_early_is_refused_and_nothing_is_published() {
    let (state, _db, root) = state_with_root().await;
    let s = open(&state, "short.mkv", 1000).await;
    let id = s["id"].as_str().unwrap().to_string();
    put_chunk(&state, &id, 0, &[3u8; 400]).await;

    let (st, v) = call(
        &state,
        "POST",
        &format!("/api/v1/uploads/{id}/complete"),
        None,
    )
    .await;
    assert_eq!(st, StatusCode::BAD_REQUEST, "{v}");
    // The staging directory must not have gained a half-file.
    let incoming = root.path().join("incoming");
    let published: Vec<_> = std::fs::read_dir(&incoming)
        .map(|d| {
            d.filter_map(|e| e.ok())
                .map(|e| e.file_name().to_string_lossy().into_owned())
                .filter(|n| n != ".sessions")
                .collect()
        })
        .unwrap_or_default();
    assert!(
        published.is_empty(),
        "nothing should be published: {published:?}"
    );
}

#[tokio::test]
async fn sending_more_than_was_declared_is_refused() {
    let (state, _db, _root) = state_with_root().await;
    let s = open(&state, "toobig.mkv", 100).await;
    let id = s["id"].as_str().unwrap().to_string();

    let (st, v) = put_chunk(&state, &id, 0, &[5u8; 400]).await;
    assert_eq!(st, StatusCode::BAD_REQUEST, "{v}");
}

#[tokio::test]
async fn a_live_session_is_listed_so_a_reload_does_not_strand_it() {
    let (state, _db, _root) = state_with_root().await;
    let s = open(&state, "listed.mkv", 400).await;
    let id = s["id"].as_str().unwrap().to_string();
    put_chunk(&state, &id, 0, &[2u8; 150]).await;

    let (st, list) = call(&state, "GET", "/api/v1/uploads", None).await;
    assert_eq!(st, StatusCode::OK);
    let rows = list.as_array().unwrap();
    assert_eq!(rows.len(), 1);
    assert_eq!(rows[0]["id"], id.as_str());
    assert_eq!(rows[0]["received_bytes"], 150);
    assert_eq!(rows[0]["filename"], "listed.mkv");
}

#[tokio::test]
async fn abandoning_a_session_removes_its_bytes() {
    let (state, _db, root) = state_with_root().await;
    let s = open(&state, "gone.mkv", 400).await;
    let id = s["id"].as_str().unwrap().to_string();
    put_chunk(&state, &id, 0, &[4u8; 200]).await;

    let (st, _) = call(&state, "DELETE", &format!("/api/v1/uploads/{id}"), None).await;
    assert_eq!(st, StatusCode::NO_CONTENT);

    assert!(!root.path().join("incoming/.sessions").join(&id).exists());
    let (st, _) = call(&state, "GET", &format!("/api/v1/uploads/{id}"), None).await;
    assert_eq!(st, StatusCode::NOT_FOUND);
}

#[tokio::test]
async fn a_session_id_from_the_url_cannot_climb_out_of_the_staging_dir() {
    let (state, _db, _root) = state_with_root().await;
    // Percent-encoded so it survives the router and reaches the handler as a
    // single path segment containing slashes.
    let (st, _) = call(&state, "GET", "/api/v1/uploads/..%2f..%2fetc", None).await;
    assert_eq!(st, StatusCode::NOT_FOUND);
}

#[tokio::test]
async fn a_kind_with_no_import_flow_cannot_open_a_session() {
    // Opening one would create a file nobody could ever finish importing.
    let (state, _db, _root) = state_with_root().await;
    let (st, v) = call(
        &state,
        "POST",
        "/api/v1/uploads",
        Some(serde_json::json!({ "filename": "x.flac", "size_bytes": 10, "kind": "music" })),
    )
    .await;
    assert_eq!(st, StatusCode::BAD_REQUEST, "{v}");
}

#[tokio::test]
async fn a_checksum_mismatch_is_caught_even_though_the_size_is_right() {
    // The failure a size check cannot see: every byte arrived, but some of
    // them are wrong. Without this, a corrupt file would be adopted into the
    // library and only discovered on playback.
    let (state, _db, _root) = state_with_root().await;
    let (st, s) = call(
        &state,
        "POST",
        "/api/v1/uploads",
        Some(serde_json::json!({
            "filename": "corrupt.wav",
            "size_bytes": 4,
            "kind": "audiobook",
            // sha256 of "good", which is not what we are about to send.
            "sha256": "5c9597f3c8245907ea71a89d9d39d08e0aca1b8b1d2d2e9d5c8b96e0e8f3a0a1"
        })),
    )
    .await;
    assert_eq!(st, StatusCode::OK, "{s}");
    let id = s["id"].as_str().unwrap().to_string();
    put_chunk(&state, &id, 0, b"bad!").await;

    let (st, v) = call(
        &state,
        "POST",
        &format!("/api/v1/uploads/{id}/complete"),
        None,
    )
    .await;
    assert_eq!(st, StatusCode::BAD_REQUEST, "{v}");
    assert!(v["message"].as_str().unwrap().contains("corrupt"), "{v}");
}

#[tokio::test]
async fn a_matching_checksum_lets_the_upload_through() {
    let (state, _db, _root) = state_with_root().await;
    let payload = tiny_wav();
    let want = sha256_hex(&payload);
    let (st, s) = call(
        &state,
        "POST",
        "/api/v1/uploads",
        Some(serde_json::json!({
            "filename": "ok.wav",
            "size_bytes": payload.len(),
            "kind": "audiobook",
            "sha256": want
        })),
    )
    .await;
    assert_eq!(st, StatusCode::OK, "{s}");
    let id = s["id"].as_str().unwrap().to_string();
    put_chunk(&state, &id, 0, &payload).await;

    let (st, v) = call(
        &state,
        "POST",
        &format!("/api/v1/uploads/{id}/complete"),
        None,
    )
    .await;
    assert_eq!(st, StatusCode::OK, "{v}");
    assert_eq!(std::fs::read(v["path"].as_str().unwrap()).unwrap(), payload);
}

// --- guards (SKADI-T-0629) --------------------------------------------------

#[tokio::test]
async fn a_file_that_is_not_media_is_refused_at_completion_and_leaves_nothing() {
    // The case this check exists for: the extension says one thing and the
    // bytes say another. library-import would have adopted it on the strength
    // of the filename alone.
    let (state, _db, root) = state_with_root().await;
    let payload = b"MZ\x90\x00this is an executable, not a film".to_vec();
    let s = open_audio(&state, "not-really.wav", payload.len()).await;
    let id = s["id"].as_str().unwrap().to_string();
    put_chunk(&state, &id, 0, &payload).await;

    let (st, v) = call(
        &state,
        "POST",
        &format!("/api/v1/uploads/{id}/complete"),
        None,
    )
    .await;
    assert_eq!(st, StatusCode::BAD_REQUEST, "{v}");
    assert!(
        v["message"]
            .as_str()
            .unwrap()
            .contains("does not read as media"),
        "{v}"
    );

    // Nothing published, and the session's bytes are gone: a file skadi will
    // not take is not a file it should be holding on the library mount.
    let incoming = root.path().join("incoming");
    let leftovers: Vec<String> = std::fs::read_dir(&incoming)
        .map(|d| {
            d.filter_map(|e| e.ok())
                .map(|e| e.file_name().to_string_lossy().into_owned())
                .filter(|n| n != ".sessions")
                .collect()
        })
        .unwrap_or_default();
    assert!(leftovers.is_empty(), "{leftovers:?}");
    assert!(!incoming.join(".sessions").join(&id).exists());
}

#[tokio::test]
async fn an_extension_with_no_reader_cannot_open_a_session() {
    // Refused at the door rather than after the upload, since the probe at
    // completion was always going to reject it.
    let (state, _db, _root) = state_with_root().await;
    for name in ["payload.exe", "notes.pdf", "archive.zip"] {
        let (st, v) = call(
            &state,
            "POST",
            "/api/v1/uploads",
            Some(serde_json::json!({
                "filename": name, "size_bytes": 10, "kind": "movie"
            })),
        )
        .await;
        assert_eq!(st, StatusCode::BAD_REQUEST, "{name}: {v}");
        assert!(
            v["message"].as_str().unwrap().contains("Accepted:"),
            "the refusal must say what is accepted: {v}"
        );
    }
}

#[tokio::test]
async fn an_audiobook_extension_is_not_accepted_as_a_film() {
    let (state, _db, _root) = state_with_root().await;
    let (st, v) = call(
        &state,
        "POST",
        "/api/v1/uploads",
        Some(serde_json::json!({
            "filename": "book.m4b", "size_bytes": 10, "kind": "movie"
        })),
    )
    .await;
    assert_eq!(st, StatusCode::BAD_REQUEST, "{v}");
}

#[tokio::test]
async fn the_operator_can_widen_the_accepted_extensions_without_a_rebuild() {
    let (state, db, _root) = state_with_root().await;
    // Refused by the built-in list.
    let (st, _) = call(
        &state,
        "POST",
        "/api/v1/uploads",
        Some(serde_json::json!({ "filename": "old.avi", "size_bytes": 10, "kind": "movie" })),
    )
    .await;
    assert_eq!(st, StatusCode::BAD_REQUEST);

    db.store
        .set_config("uploads.allowed_extensions", "avi", ConfigSource::Runtime)
        .await
        .unwrap();

    let (st, v) = call(
        &state,
        "POST",
        "/api/v1/uploads",
        Some(serde_json::json!({ "filename": "old.avi", "size_bytes": 10, "kind": "movie" })),
    )
    .await;
    assert_eq!(st, StatusCode::OK, "{v}");
}

#[tokio::test]
async fn a_file_larger_than_the_disk_is_refused_before_a_byte_is_sent() {
    // Discovering at 95% that it was never going to fit is the worst version
    // of this failure.
    let (state, _db, _root) = state_with_root().await;
    let (st, v) = call(
        &state,
        "POST",
        "/api/v1/uploads",
        Some(serde_json::json!({
            "filename": "huge.mkv",
            // Larger than any real filesystem this will run on.
            "size_bytes": 900_000_000_000_000u64,
            "kind": "movie"
        })),
    )
    .await;
    assert_eq!(st, StatusCode::BAD_REQUEST, "{v}");
    assert!(v["message"].as_str().unwrap().contains("free"), "{v}");
}

#[tokio::test]
async fn nothing_in_the_staging_directory_can_be_fetched_over_http() {
    // Staging is an *input*, not a library location. The first version of this
    // test asserted a 404 on `/incoming` and failed: the web app's
    // single-page-app fallback answers 200 with index.html for any unknown
    // path. That is not a leak, and testing for a status code was testing the
    // wrong thing — what matters is that the *bytes* are unreachable.
    let (state, _db, root) = state_with_root().await;
    let secret = b"STAGED-BYTES-THAT-MUST-NOT-BE-SERVED";
    let incoming = root.path().join("incoming");
    std::fs::create_dir_all(&incoming).unwrap();
    std::fs::write(incoming.join("private.mkv"), secret).unwrap();

    for uri in [
        "/incoming/private.mkv",
        "/api/v1/incoming/private.mkv",
        "/app/private.mkv",
        "/api/v1/uploads/../incoming/private.mkv",
    ] {
        let req = Request::builder()
            .method("GET")
            .uri(uri)
            .header("Authorization", "Bearer operator-token")
            .body(Body::empty())
            .unwrap();
        let res = skadi_api::router(state.clone()).oneshot(req).await.unwrap();
        let body = res.into_body().collect().await.unwrap().to_bytes();
        assert!(
            !body.windows(secret.len()).any(|w| w == secret),
            "{uri} served the staged file's contents"
        );
    }
}

#[test]
fn the_sweep_removes_a_session_nothing_has_touched() {
    // Unit-level because the loop is hourly; the behaviour under test is the
    // age comparison, not the scheduler.
    let tmp = tempfile::tempdir().unwrap();
    let stale = tmp.path().join("stale");
    std::fs::create_dir_all(&stale).unwrap();
    std::fs::write(stale.join("part"), b"abandoned").unwrap();
    std::fs::write(stale.join("manifest.json"), b"{}").unwrap();

    // A TTL of one hour against a file written just now leaves it; the age
    // comparison is what matters, so drive it with a zero-hour TTL clamped to
    // one and a backdated file instead.
    let removed = skadi_api::uploads::sweep_sessions(tmp.path(), 1);
    assert!(
        removed.is_empty(),
        "a fresh session must survive: {removed:?}"
    );
    assert!(stale.exists());
}

// --- access (SKADI-T-0630) --------------------------------------------------

/// Create a member with the given role and return its token.
async fn member_token(state: &Arc<AppState>, name: &str, role: &str) -> String {
    let (st, v) = call(
        state,
        "POST",
        "/api/v1/members",
        Some(serde_json::json!({ "name": name, "role": role })),
    )
    .await;
    assert_eq!(st, StatusCode::CREATED, "creating {name}: {v}");
    v["token"].as_str().unwrap().to_string()
}

async fn call_as(
    state: &Arc<AppState>,
    token: &str,
    method: &str,
    uri: &str,
    body: Option<serde_json::Value>,
) -> (StatusCode, serde_json::Value) {
    let req = Request::builder()
        .method(method)
        .uri(uri)
        .header("Authorization", format!("Bearer {token}"));
    let req = match body {
        Some(b) => req
            .header("content-type", "application/json")
            .body(Body::from(b.to_string()))
            .unwrap(),
        None => req.body(Body::empty()).unwrap(),
    };
    let res = skadi_api::router(state.clone()).oneshot(req).await.unwrap();
    let status = res.status();
    let bytes = res.into_body().collect().await.unwrap().to_bytes();
    (
        status,
        serde_json::from_slice(&bytes).unwrap_or(serde_json::Value::Null),
    )
}

#[tokio::test]
async fn a_contributor_can_upload_but_a_read_only_member_is_refused() {
    let (state, _db, _root) = state_with_root().await;
    let contributor = member_token(&state, "Uploader", "contributor").await;
    let reader = member_token(&state, "Reader", "member").await;
    let body = serde_json::json!({
        "filename": "a.mkv", "size_bytes": 10, "kind": "movie"
    });

    let (st, v) = call_as(
        &state,
        &contributor,
        "POST",
        "/api/v1/uploads",
        Some(body.clone()),
    )
    .await;
    assert_eq!(st, StatusCode::OK, "{v}");

    let (st, _) = call_as(&state, &reader, "POST", "/api/v1/uploads", Some(body)).await;
    assert_eq!(st, StatusCode::FORBIDDEN);
}

#[tokio::test]
async fn one_contributor_cannot_touch_another_contributors_upload() {
    // Two people with the same role. Sharing a role is not sharing a session.
    let (state, _db, _root) = state_with_root().await;
    let alice = member_token(&state, "Alice", "contributor").await;
    let bob = member_token(&state, "Bob", "contributor").await;

    let (st, s) = call_as(
        &state,
        &alice,
        "POST",
        "/api/v1/uploads",
        Some(serde_json::json!({ "filename": "hers.mkv", "size_bytes": 50, "kind": "movie" })),
    )
    .await;
    assert_eq!(st, StatusCode::OK, "{s}");
    let id = s["id"].as_str().unwrap().to_string();

    // A 404 rather than a 403: Bob has no business learning which session ids
    // exist, and that distinction is exactly what the status code leaks.
    for (m, uri) in [
        ("GET", format!("/api/v1/uploads/{id}")),
        ("POST", format!("/api/v1/uploads/{id}/complete")),
        ("DELETE", format!("/api/v1/uploads/{id}")),
    ] {
        let (st, v) = call_as(&state, &bob, m, &uri, None).await;
        assert_eq!(st, StatusCode::NOT_FOUND, "{m} {uri}: {v}");
    }

    // And Alice's session is untouched.
    let (st, v) = call_as(
        &state,
        &alice,
        "GET",
        &format!("/api/v1/uploads/{id}"),
        None,
    )
    .await;
    assert_eq!(st, StatusCode::OK, "{v}");
}

#[tokio::test]
async fn a_contributor_sees_only_their_own_sessions_in_the_list() {
    let (state, _db, _root) = state_with_root().await;
    let alice = member_token(&state, "Alice", "contributor").await;
    let bob = member_token(&state, "Bob", "contributor").await;
    for t in [&alice, &bob] {
        call_as(
            &state,
            t,
            "POST",
            "/api/v1/uploads",
            Some(serde_json::json!({ "filename": "x.mkv", "size_bytes": 20, "kind": "movie" })),
        )
        .await;
    }

    let (_, mine) = call_as(&state, &alice, "GET", "/api/v1/uploads", None).await;
    assert_eq!(mine.as_array().unwrap().len(), 1);

    // The operator sees everything, as everywhere else.
    let (_, all) = call(&state, "GET", "/api/v1/uploads", None).await;
    assert_eq!(all.as_array().unwrap().len(), 2);
}

#[tokio::test]
async fn the_admin_can_clean_up_somebody_elses_abandoned_session() {
    let (state, _db, _root) = state_with_root().await;
    let alice = member_token(&state, "Alice", "contributor").await;
    let (_, s) = call_as(
        &state,
        &alice,
        "POST",
        "/api/v1/uploads",
        Some(serde_json::json!({ "filename": "stuck.mkv", "size_bytes": 20, "kind": "movie" })),
    )
    .await;
    let id = s["id"].as_str().unwrap().to_string();

    let (st, _) = call(&state, "DELETE", &format!("/api/v1/uploads/{id}"), None).await;
    assert_eq!(st, StatusCode::NO_CONTENT);
}

#[tokio::test]
async fn a_chunk_larger_than_the_global_limit_still_goes_through() {
    // The point of the chunk route's own limit. Under the global 16 MB ceiling
    // this would be fine anyway, so the assertion that matters is that a body
    // well past what any JSON route accepts is not rejected here.
    let (state, _db, _root) = state_with_root().await;
    let big = vec![0u8; 20 * 1024 * 1024];
    let s = open(&state, "big.mkv", big.len()).await;
    let id = s["id"].as_str().unwrap().to_string();

    let (st, v) = put_chunk(&state, &id, 0, &big).await;
    assert_eq!(
        st,
        StatusCode::OK,
        "a 20 MB chunk must be accepted by the chunk route: {v}"
    );
    assert_eq!(v["received_bytes"], big.len());
}

#[tokio::test]
async fn an_ordinary_route_refuses_an_enormous_body() {
    // Before SKADI-T-0630 the daemon set no limit at all, so axum's
    // unconfigured 2 MB default applied everywhere by accident. The limit is
    // chosen now, and this proves there is one.
    let (state, _db, _root) = state_with_root().await;
    let huge = "x".repeat(20 * 1024 * 1024);
    let req = Request::builder()
        .method("POST")
        .uri("/api/v1/uploads")
        .header("Authorization", "Bearer operator-token")
        .header("content-type", "application/json")
        .body(Body::from(
            serde_json::json!({ "filename": huge, "size_bytes": 1, "kind": "movie" }).to_string(),
        ))
        .unwrap();
    let res = skadi_api::router(state.clone()).oneshot(req).await.unwrap();
    assert_eq!(res.status(), StatusCode::PAYLOAD_TOO_LARGE);
}

// --- the hand-off to library-import (SKADI-T-0632) --------------------------

#[tokio::test]
async fn staging_shares_a_filesystem_with_the_library_root() {
    // The failure this whole design is arranged to avoid. `restructure_into`
    // refuses a cross-device move and tells the operator to scan through the
    // same mount, so a staging directory on a different filesystem would
    // upload perfectly and then fail at commit — after a long upload, which is
    // the worst possible place to discover it.
    //
    // Asserted here so a future compose change that splits them fails loudly
    // and early rather than at somebody's 40 GB film.
    use std::os::unix::fs::MetadataExt;

    let (state, _db, root) = state_with_root().await;
    let incoming = skadi_api::uploads::incoming_dir(&state).await.unwrap();
    std::fs::create_dir_all(&incoming).unwrap();

    assert!(
        incoming.starts_with(root.path()),
        "staging must live under library.root, got {}",
        incoming.display()
    );
    let lib_dev = std::fs::metadata(root.path()).unwrap().dev();
    let staging_dev = std::fs::metadata(&incoming).unwrap().dev();
    assert_eq!(
        lib_dev, staging_dev,
        "staging is on a different filesystem from the library root — \
         an import from it would hit the cross-device refusal"
    );
}

#[tokio::test]
async fn a_completed_upload_answers_a_path_the_import_scan_can_take() {
    // The hand-off contract: `complete` answers a real, absolute, existing
    // server path, which is exactly what library-import's scan takes. Nothing
    // about an uploaded file is special once it is there.
    let (state, _db, root) = state_with_root().await;
    let payload = tiny_wav();
    let s = open_audio(&state, "Handed Over.wav", payload.len()).await;
    let id = s["id"].as_str().unwrap().to_string();
    put_chunk(&state, &id, 0, &payload).await;

    let (st, done) = call(
        &state,
        "POST",
        &format!("/api/v1/uploads/{id}/complete"),
        None,
    )
    .await;
    assert_eq!(st, StatusCode::OK, "{done}");

    let path = std::path::PathBuf::from(done["path"].as_str().unwrap());
    assert!(path.is_absolute(), "{path:?}");
    assert!(path.exists(), "{path:?}");
    assert!(path.starts_with(root.path()), "{path:?}");
    // The filename survives, because the importer and the matcher both read it.
    assert_eq!(path.file_name().unwrap(), "Handed Over.wav");
    // And the kind comes back, so the UI knows which import page to open.
    assert_eq!(done["kind"], "audiobook");

    // The session is spent: its directory is gone, so the sweep has nothing
    // to do and a reload does not offer to resume a finished upload.
    assert!(!root.path().join("incoming/.sessions").join(&id).exists());
    let (_, list) = call(&state, "GET", "/api/v1/uploads", None).await;
    assert!(list.as_array().unwrap().is_empty(), "{list}");
}

#[tokio::test]
async fn an_abandoned_upload_stays_staged_rather_than_half_imported() {
    // Walking away at the identify step must leave a whole file that the
    // sweep can deal with, not a partial one in the library.
    let (state, _db, root) = state_with_root().await;
    let payload = tiny_wav();
    let s = open_audio(&state, "Left Alone.wav", payload.len()).await;
    let id = s["id"].as_str().unwrap().to_string();
    put_chunk(&state, &id, 0, &payload).await;
    call(
        &state,
        "POST",
        &format!("/api/v1/uploads/{id}/complete"),
        None,
    )
    .await;

    // Staged and whole. Nothing has touched the library folders.
    let staged = root
        .path()
        .join("incoming")
        .join(&id)
        .join("Left Alone.wav");
    assert_eq!(std::fs::read(&staged).unwrap(), payload);
    for domain in ["movie", "television", "audiobook"] {
        assert!(
            !root.path().join(domain).exists(),
            "{domain} should be untouched until a commit"
        );
    }
}
