import { chromium } from "@playwright/test";
const BASE = "http://127.0.0.1:8090";
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
const errors = [];
page.on("console", m => { if (m.type() === "error") errors.push(m.text().slice(0, 160)); });
await page.goto(BASE + "/", { waitUntil: "networkidle", timeout: 25000 }).catch(() => {});
await page.waitForTimeout(1200);
await page.locator('text=+ Add media').first().click().catch(e => console.log("click failed:", e.message.slice(0,100)));
await page.waitForTimeout(1200);
console.log("after Add media -> url=" + page.url());
console.log("h2/h3:", await page.locator("h2, h3").first().textContent().catch(() => "?"));
console.log("console errors:", JSON.stringify(errors));
await browser.close();
