author_email = "dylanbstorey@users.noreply.github.com"
author_name = "Dylan Storey"
github_org = "skadi-media"
include_python_bindings = "false"
include_ui = "false"
initial_version = "0.0.1"
license = "MIT OR Apache-2.0"
project_description = "A unified, Rust-native replacement for the *arr stack"
project_name = "Skadi"
project_slug = "skadi"
rust_version = "1.93"
